### ISSUE TITLE
Замечания по лабораторной работе №3

### ISSUE THREAD

**Issue by volgatech-web-development** [MishaMukhorin/Web-development#2]
**общие замечания**
- [x]  именование переменных, функций и форматирование не по соглашению. Изучить https://docs.google.com/document/d/1Rfb0ol6OQZygOqNmT2Zc3oaDHCA04iVLs-fkX9Qy7TE/edit и исправить
Переменные лучше именовать не просто одной буквой, а словом или словами
например 
`
$S = $_GET['text'];
`
лучше назвать 
`$textParam = $_GET['text'];`

Функции - это действия, поэтому называть нужно используя глагол, например 
`function isLetter($character)`

- [x] зарезервированные слова пишем маленькими буквами везде
![image](https://user-images.githubusercontent.com/63309827/81468616-55bbcd00-91e9-11ea-9732-c650d2653af3.png)

- [x] код в блоках if, else, elseif пиiем в {}, даже если код состоит из одной строки 

- [x] добавить проверки на отсутствие параметра и на его пустоту

**задание 1**
- [x] нет проверки на то, что параметр не передан или если он пустой. Добавить эти проверки
![image](https://user-images.githubusercontent.com/63309827/81468695-c82cad00-91e9-11ea-8de0-4a2358571b78.png)
![image](https://user-images.githubusercontent.com/63309827/81468732-032ee080-91ea-11ea-8a88-f5d125652b38.png)

- [x] программа не должна выдавать notice. Исправить и тщательно протестировать все случаи: 
1. параметр не передан
2. передан, но пустой
3. всевозможные варианты текста: без пробелов, много пробелов в начале, в конце и тд 
![image](https://user-images.githubusercontent.com/63309827/81468751-26f22680-91ea-11ea-98f6-fb25af96c63d.png)

**задание 2**
- [x] параметр должен называться identifier
![image](https://user-images.githubusercontent.com/63309827/81468821-8e0fdb00-91ea-11ea-9bf9-4985ebd97b8f.png)

- [x] пустая строка НЕ может быть идентификатором
![image](https://user-images.githubusercontent.com/63309827/81468856-b1d32100-91ea-11ea-96f1-c9f4746e45ea.png)

**задание 4**
- [x] добавить проверки наличие параметров, тк некоторые из них могут отсутствовать
![image](https://user-images.githubusercontent.com/63309827/81469013-6bca8d00-91eb-11ea-925c-0720ec78ec8d.png)

- [x] сохранение работает некорректно
вывод был: ?email=a@email.com
а сохранилось вот:
![image](https://user-images.githubusercontent.com/63309827/81469054-94528700-91eb-11ea-8bac-2103175b5320.png)
Должно сохраняться в виде:
First Name: <name>
Last Name: ...
Email: <email>
Age: 30

**задание 5**
- [x]  убрать notice 
![image](https://user-images.githubusercontent.com/63309827/81469140-0b881b00-91ec-11ea-8cac-af3e5da1525f.png)

- [x] если файла не существует, то падает warning. Нужно избавиться от него
![image](https://user-images.githubusercontent.com/63309827/81469153-1f338180-91ec-11ea-9e01-d67ec6f157ba.png)

**Comment by MishaMukhorin** [comment]
все выполнено, можно проверять.
